// ============================================================
// YOUR MEMOS LIVE HERE.
// To publish a new memo: copy the block below, fill it in,
// and add it anywhere in this list (order doesn't matter —
// the page sorts by date automatically). Then commit the file.
//
// Required fields: ticker, company, date, call, thesis
// Optional fields: conviction, priceTarget, catalysts, risks, notes
// call must be one of: "BUY", "HOLD", "SELL", "WATCH"
// date format: "YYYY-MM-DD"
// ============================================================

const MEMOS = [
  {
  ticker: "TSLA",
  company: "Tesla, Inc.",
  date: "2026-07-03",
  call: "WATCH",
  conviction: "Low-Medium — thesis stage",
  priceTarget: "",
  thesis: `The most useful data point I found on this company wasn't in the 10-K — it was in a demo video. At a recent event, an Optimus V2.3 unit served popcorn to attendees. It moved smoothly, with none of the jitter you'd expect from early-stage hardware. But it was also visibly teleoperated, running basic scripted instructions rather than independent judgment — and the people interacting with it didn't find it unsettling. My read: we don't fear machines that clearly lack independent judgment, no matter how smooth their movements are. We fear the presence of intelligence that could outmatch our own. Right now, everyone watching Optimus knows a person is driving it. The moment that stops being visibly true is the moment public sentiment around this technology shifts. That threshold isn't in any analyst model I've seen, but I think it's the real trigger the market is implicitly pricing without naming.

Financially, the near-term picture doesn't support paying up for that bet yet. Automotive is still 73% of revenue, and it's the segment eroding — operating margin has fallen every year since 2022, from roughly 17% down to 4.6% in 2025, a trend that predates the robotics narrative entirely. The one segment actually accelerating is the least glamorous one: energy storage (Megapack, Powerwall), up 27% year-over-year. Meanwhile R&D spend rose over 40%, explicitly funneled into AI and robotics. At today's valuation, an investor isn't buying "Tesla, car company." They're buying "Tesla, a bet that the robotics story matures faster than the core business erodes," priced with very little room to be wrong about timing.

The honest tension I keep landing on is that Tesla's scale is real, but scale in car manufacturing doesn't automatically prove out in robot manufacturing — those aren't the same supply chain, and I haven't seen evidence yet that they are. What actually moves me toward WATCH instead of SELL is the energy segment growing 27% underneath all this noise, quietly, without anyone's attention on it. That's the part of this company I'd trust with money today. The robotics bet is the part I'd want to watch, not fund yet — and I think that distinction matters more than any bull/bear scorecard.`,
  catalysts: `A deployment milestone where Optimus performs an unscripted task on a live factory floor — the clearest sign the "intelligence becomes visible" threshold is approaching. Confirmed movement toward the commercial sale window management has floated for consumers (2027-2028 has been mentioned publicly; not yet verified against a direct Tesla source). Regulatory clarity — a bill is currently sitting in Congress (the Humanoid ROBOT Act), text not yet published as of late June 2026. Any earnings call where management reports a real Optimus usage metric instead of a demo update. Continued energy-segment growth outpacing automotive — if this becomes the recognized growth story, that's a different, more grounded thesis than the robotics narrative.`,
  risks: `Automotive operating margin has declined for three straight years (17% in 2022 to 4.6% in 2025) — the core cash engine is deteriorating independent of the robotics bet. Valuation (P/E roughly 360-386x as of early July 2026) already prices in significant optionality, leaving little room for a slower timeline. Musk has a well-documented pattern of ambitious robotics/autonomy timelines slipping; that history should discount any new target date, including 2027-2028. China reportedly accounts for the large majority of humanoid robot installations globally at a fraction of Western unit cost (approximate, sourced from press coverage rather than a filing). Global regulation is undefined; could accelerate or delay adoption depending how it resolves. Three things that would invalidate this thesis entirely: Tesla quietly deprioritizes Optimus; automotive margins keep compressing toward breakeven with no Optimus revenue by 2027-2028; or a safety incident/credibility issue around how autonomous the public demos actually are.`,
  notes: `Worth naming honestly: this pick sits outside the fintech/behavioral niche I'm building this portfolio around. Publishing it deliberately alongside a fintech memo the same week so my actual focus is visible from day one. To verify before/after publishing: exact Optimus commercial timeline, extent of teleoperation vs. autonomy in public demos, status of the Humanoid ROBOT Act text, China unit-cost figures, and a direct balance-sheet ROIC build (this uses a vendor-calculated ~6.3% ROIC, not one I reconstructed myself from NOPAT and invested capital).`
},
  {
  ticker: "KLAR",
  company: "Klarna Group plc",
  date: "2026-07-06",
  call: "WATCH",
  conviction: "Low-Medium — thesis stage",
  priceTarget: "",
  thesis: `Klarna's core design choice — approve fast, keep friction near zero, don't make the debt feel like debt — is also the thing that's now blindsided three completely different groups within about a year of each other. Mortgage brokers report BNPL usage tanking otherwise-qualified applicants because the aggregate shows up on bank statements even where it doesn't touch a credit score. IPO investors got blindsided when Q3 2025 provisions for credit losses jumped 102% year-over-year ($116M to $235M, per Klarna's own filings) just months after a prospectus a securities class action now alleges understated exactly this risk — down to specifically flagging that customers were financing things like fast-food delivery on installment. And in December 2025, a viral "Klarna glitch" trend turned out to be identity thieves exploiting the same fast, low-friction approval process to open fraudulent accounts in stolen names, leaving innocent people with debt and wrecked credit. Three stakeholders, one mechanism: minimizing visible scrutiny at approval is exactly what makes the product loved at checkout and exactly what makes it capable of surprising someone — a borrower, an investor, a fraud victim — later, once the friction that was removed turns out to have been doing real work.

The financial picture is a genuine recovery story sitting inside that same tension, not a settled one. Q1 2026 revenue hit $1.01B, up 44% year-over-year, with adjusted operating profit of $68M versus just $3M a year earlier — real operating leverage, not a one-off. Provisions for credit losses as a share of GMV have also been declining (0.72% in Q3 2025 to 0.65% in Q4), which Klarna presents as evidence its underwriting is maturing, not concealing risk. I don't think that claim is false, but I also don't think it resolves the lawsuit's core question, which is what Klarna knew at the moment of the IPO, not what its numbers look like a few quarters later. The stock is still trading roughly 50%+ below its $40 IPO price as of mid-2026 (exact level worth checking day-of), which tells me the market hasn't decided this is resolved either.`,
  catalysts: `The thing I'm actually watching is the securities lawsuit, not the next earnings print — Nayak v. Klarna Group is asking a more interesting question than any quarterly number can answer, which is what Klarna's own models actually showed before the IPO, not just what the numbers look like a few quarters later. If discovery in that case surfaces internal risk modeling that contradicts the prospectus, that's the moment this thesis either gets much darker or gets resolved in Klarna's favor. Short of that, Q2 2026 earnings matter mainly as a test of whether Q1's declining loss-provision rate was a real trend or a lucky quarter — one data point isn't a pattern yet. I'm also watching for any regulatory response to the "glitch" fraud wave, since a CFPB or Congressional look at how little friction sits between "click buy" and "get approved" would hit the exact mechanism this whole memo is about, not just a PR problem. And if Fair Financing keeps growing at the clip it did in Q1 2026 (up 138% year-over-year) and starts outgrowing Pay-in-4, that quietly changes the thesis itself — Fair Financing reports to bureaus, so a Klarna that's mostly Fair Financing isn't really the "invisible debt" company anymore.`,
  risks: `That lawsuit cuts both ways, which is the real risk sitting underneath everything else here — if discovery shows Klarna's internal credit models flagged the risk that showed up as a 102% provision spike in Q3 2025, and the prospectus still didn't disclose it, that's a different and much worse story than "growth company hit a rough patch." Sitting underneath that is a prior pattern worth naming honestly: Sweden's FSA reportedly fined Klarna around $46 million in December 2024 for anti-money-laundering violations, before any of this — I haven't traced that figure to a primary regulatory filing myself, so it's worth confirming, but if accurate it suggests this isn't the company's first brush with "risk controls under fire," which matters for how much benefit of the doubt the current recovery story deserves. The stock itself is still down somewhere in the 50-65%+ range from its IPO price depending on which source and date you check — genuinely worth pulling a live quote before this goes out, since the sources I found don't agree. What would actually break the recovery half of this thesis is simple: provisions for credit losses turning back upward as a share of GMV, not just in dollar terms, since dollar growth alone is expected as the loan book scales.`,
  notes: `Primary-sourced this round from Klarna's actual SEC 6-K filings (quarterly P&L, Q1'24 through Q1'26) rather than secondary write-ups — provision-for-credit-losses figures and the 102% YoY figure are confirmed against Klarna's own numbers. Still need to verify: current live stock price (conflicting recent figures); primary source for the Sweden FSA fine; current status of the Nayak lead-plaintiff process past the Feb 20, 2026 deadline; whether "Klarna glitch" prompted any regulatory statement from Klarna itself or the CFPB.`
}
];
